2024-02-06 14:32:18,100 - ERROR - Exception: 'data'
2024-02-07 08:58:08,243 - ERROR - HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /vending_status/?ip_address=192.168.1.4 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x000002F009614A70>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-07 14:34:58,518 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /checkout/?user_id=1234567891&product_id=87 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020FD0F9EF30>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-07 14:53:01,750 - ERROR - Exception: HTTPConnectionPool(host='192.168.1.4', port=8000): Max retries exceeded with url: /check_user/?user_id=1234567891&ip_address=192.168.1.4 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000020FD0F45160>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2024-02-07 14:53:38,492 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /checkout/?user_id=1234567891&product_id=87 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020FD0FF2300>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
2024-02-07 14:53:54,316 - ERROR - Error processing takeout request: HTTPConnectionPool(host='192.168.18.110', port=8000): Max retries exceeded with url: /checkout/?user_id=1234567891&product_id=90 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x0000020FD0FCA2A0>, 'Connection to 192.168.18.110 timed out. (connect timeout=None)'))
