2024-03-26 09:12:59,053 - ERROR - HTTPConnectionPool(host='10.30.22.11', port=5340): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x70437ca14df0>, 'Connection to 10.30.22.11 timed out. (connect timeout=None)'))
2024-03-27 08:50:04,093 - ERROR - Failed to checkout!
Error message: Expecting value: line 1 column 1 (char 0)
2024-03-27 08:51:45,295 - ERROR - Exception: 'data'
2024-03-27 09:02:28,651 - ERROR - Failed to checkout!
Error message: Expecting value: line 1 column 1 (char 0)
2024-03-27 10:40:13,141 - ERROR - Failed to checkout!
Error message: Expecting value: line 1 column 1 (char 0)
2024-03-27 12:24:31,382 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3c2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:24:38,230 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1c60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:24:44,524 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2dd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:24:50,384 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:24:56,060 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb29e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:02,622 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1e70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:09,356 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0df0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:16,323 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1420>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:23,184 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb24d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:30,041 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca35b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:37,014 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3550>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:42,877 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1bd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:49,706 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb35e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:25:55,587 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:01,593 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1c60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:07,626 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2d70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:13,693 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:20,426 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1480>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:27,184 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1d50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:34,250 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1990>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:41,111 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3700>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:48,071 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2aa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:26:54,833 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0ee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:01,083 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1000>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:07,633 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:14,297 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3880>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:20,945 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1e40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:30,161 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:37,025 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:43,780 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2a70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:50,641 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:27:57,509 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2230>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:04,363 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:11,125 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:17,880 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb20e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:23,905 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3340>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:30,885 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:37,862 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb21a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:44,804 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb10f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:50,867 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2770>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:28:57,248 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:04,066 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b985b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:10,136 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb36d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:16,238 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:22,295 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2f20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:28,379 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:34,457 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb35e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:40,495 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99330>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:46,578 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb35e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:52,641 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb23e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:29:58,705 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:05,032 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:11,098 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:17,279 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:23,332 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:29,330 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb31c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:35,389 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99330>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:41,434 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:47,512 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0cd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:30:54,390 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9af20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:01,316 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b5bfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:08,276 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb21a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:15,236 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2680>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:22,192 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2cb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:29,476 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1630>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:36,125 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:43,026 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1450>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:50,154 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb27a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:31:56,888 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3250>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:03,773 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:10,941 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2e60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:17,600 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:24,345 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1570>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:31,014 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb25f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:37,734 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2f20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:44,220 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b588e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:50,883 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1db0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:32:56,564 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1e40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:02,564 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:08,808 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1570>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:15,213 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:21,236 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b587f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:27,842 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2e60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:34,553 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:41,409 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2860>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:47,499 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2da0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:33:53,954 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a470>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:00,234 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:06,770 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb14b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:13,106 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:19,759 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58760>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:25,998 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1c60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:32,661 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:39,522 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:46,382 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1ba0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:52,936 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9af50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:34:59,551 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b587f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:06,248 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1f60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:12,759 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1600>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:19,458 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a70af4c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:26,318 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb17e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:33,538 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb37c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:39,622 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2500>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:46,303 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2aa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:53,352 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2bf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:35:59,909 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3670>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:06,459 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:13,231 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1c60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:19,979 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2470>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:26,632 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:33,383 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca30a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:39,258 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb22f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:45,329 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:51,898 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1270>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:36:58,077 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:04,615 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:11,684 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3280>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:18,548 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3190>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:24,550 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:31,246 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1840>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:37,744 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:44,356 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:50,421 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2650>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:37:57,153 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:03,265 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1270>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:09,748 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98160>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:16,606 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb34f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:22,633 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb18a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:29,094 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b994b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:35,121 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:42,107 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:48,133 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b990c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:38:54,174 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:00,196 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb29e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:06,369 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:12,820 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a5f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:18,904 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:25,518 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:32,484 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a560>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:38,839 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a620>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:45,202 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99d80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:51,841 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99240>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:39:58,807 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b996c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:05,767 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a6e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:12,526 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b998d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:19,489 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99720>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:25,410 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:32,183 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99330>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:39,150 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b991e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:46,011 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a590>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:40:53,076 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98d60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:00,247 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:07,003 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:13,676 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:19,746 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:26,154 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb10f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:32,793 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9be50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:38,937 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b991e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:45,508 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:52,366 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99570>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:41:58,461 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bbb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:05,370 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99120>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:12,337 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:18,394 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:24,976 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2830>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:31,687 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:38,346 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99660>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:44,434 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:50,839 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1fc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:42:57,393 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a7a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:03,425 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b987f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:10,388 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:17,168 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb17b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:24,014 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb35e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:30,875 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:37,428 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2bc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:43,397 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1ff0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:49,384 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3370>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:43:55,395 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1d80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:02,206 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3010>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:09,480 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2b60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:15,627 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2860>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:22,587 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2890>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:28,577 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:35,254 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:41,311 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2ef0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:47,198 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:53,021 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb34f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:44:59,052 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:04,979 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb18d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:10,906 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3370>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:17,576 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:23,576 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58850>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:30,785 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb21d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:37,459 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3a00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:44,302 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb33a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:51,064 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3820>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:45:57,723 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:03,748 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca31c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:10,619 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:17,582 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98700>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:24,555 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55b70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:31,304 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:38,267 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:44,400 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:51,272 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1e70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:46:57,928 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b989d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:04,789 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:11,752 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb10f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:18,467 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3280>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:24,931 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb24a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:31,659 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1c60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:38,376 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb29b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:45,135 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:51,897 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:47:58,549 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0d30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:05,205 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb23e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:11,109 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:18,216 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:24,968 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3730>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:31,159 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:37,968 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2470>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:44,036 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2470>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:50,364 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:48:56,757 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:02,901 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:09,038 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb15a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:15,657 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3a60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:21,910 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:28,578 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:35,218 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3070>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:41,974 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d7e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:48,633 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:49:54,774 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99300>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:01,634 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d7e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:08,700 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1c00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:15,356 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:21,538 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:27,837 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2470>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:34,537 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:41,359 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b587f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:48,124 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1a20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:50:54,780 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a230>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:02,141 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d8a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:08,744 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2f80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:14,663 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2620>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:20,536 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca33d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:27,139 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2860>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:33,389 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb26e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:40,041 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d8d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:46,697 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1060>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:51:53,456 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb29b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:00,112 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:06,048 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3160>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:12,817 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1e40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:18,921 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:25,474 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2c20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:32,343 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca3700>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:39,126 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0b20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:45,644 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3400>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:51,927 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1780>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:52:58,887 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1330>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:05,648 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3e20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:13,123 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2c20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:19,785 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:26,435 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1630>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:32,518 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1840>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:39,236 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1300>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:45,630 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2080>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:52,383 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:53:59,299 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1270>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:06,164 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb15a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:12,670 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9ba60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:19,118 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb21d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:25,670 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1810>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:32,696 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:39,186 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a3b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:45,121 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1b70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:51,273 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1360>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:54:57,356 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:04,330 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9afe0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:10,439 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b981f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:16,545 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b3a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:22,967 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:29,828 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9baf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:35,897 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a080>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:42,022 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99ff0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:48,149 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:55:54,238 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b970>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:00,241 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a860>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:06,905 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2aa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:14,065 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a080>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:20,824 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:27,483 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1120>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:34,238 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9ae00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:41,099 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99960>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:47,747 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb14e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:56:54,405 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9abc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:01,173 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a1a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:08,235 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:14,994 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:21,752 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:28,718 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1570>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:35,474 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99120>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:42,334 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:48,991 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1060>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:57:55,138 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:01,995 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a5c0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:08,746 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb32e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:15,413 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b8b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:22,271 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9ac80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:29,029 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:35,838 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98d90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:42,757 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99750>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:49,304 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb25f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:58:55,858 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:02,617 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1b10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:09,276 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2d40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:16,437 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:23,503 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0f10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:29,566 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3490>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:35,886 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58670>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:42,450 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1960>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:48,847 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b994e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 12:59:54,996 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d5d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:01,524 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:08,454 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb38b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:15,219 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3fa0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:21,977 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1cf0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:28,735 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b989a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:35,596 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d8a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:42,256 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1960>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:49,219 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99a80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:00:55,769 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1f60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:02,568 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb22f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:09,128 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99120>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:15,681 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:21,796 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3610>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:28,537 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:35,398 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2ce0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:42,166 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1ab0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:48,539 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:01:55,465 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:02,103 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb15a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:08,522 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99240>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:14,574 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b588e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:20,648 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1510>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:26,696 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98580>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:32,987 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1a50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:39,117 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:45,589 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b989a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:51,723 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d8a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:02:57,676 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1fc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:03,573 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2a10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:09,722 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1f30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:16,676 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb20e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:23,629 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb39d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:29,882 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1cc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:36,745 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2e30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:43,335 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:50,053 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:03:56,810 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb33a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:03,462 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98d00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:10,121 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d690>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:16,872 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb26e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:23,841 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9ba30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:30,599 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5c55900>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:37,466 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1480>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:44,425 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9aa10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:51,378 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58520>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:04:58,136 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1d80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:04,696 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99e10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:10,941 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb36d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:18,007 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0ca0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:24,021 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b670>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:31,109 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3220>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:37,661 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2080>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:44,424 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bfd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:50,749 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2110>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:05:57,472 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3e80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:03,994 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:11,155 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b58670>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:17,804 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:23,892 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:30,496 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:36,591 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2950>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:43,402 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b989d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:50,057 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b588e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:06:57,020 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2c50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:04,000 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:11,451 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b3d7e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:18,311 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1f00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:24,605 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b5b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:31,319 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb15d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:37,977 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3dc0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:44,947 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99d20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:51,596 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2980>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:07:57,842 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0c70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:04,600 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:11,358 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1090>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:17,516 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:23,748 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98f70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:30,403 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1b70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:37,161 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2d70>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:43,919 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:50,680 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2f50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:08:57,128 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0eb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:03,291 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b6a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:10,146 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3040>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:15,985 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2ec0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:21,958 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a920>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:29,178 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bf10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:36,141 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3bb0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:42,905 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2320>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:49,561 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2b90>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:09:56,210 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:02,968 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98820>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:09,419 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b2e0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:16,177 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3790>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:22,673 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0f40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:29,488 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb15a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:36,246 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3700>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:43,305 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98940>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:49,911 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a5ca2f80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:10:56,726 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b0d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:03,351 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bc40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:10,242 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9af20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:16,916 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99f30>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:23,971 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:30,625 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a980>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:37,274 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a5f0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:44,346 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2f20>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:50,995 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a050>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:11:57,651 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98c40>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:04,614 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb0e50>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:11,363 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:18,331 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98910>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:24,991 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1720>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:31,749 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b99c00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:38,712 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98310>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:45,224 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb2e60>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:51,960 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb20b0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:12:58,980 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b820>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:05,949 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bee0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:12,503 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b98c10>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:20,694 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a290>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:27,760 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3fd0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:34,518 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb1840>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:41,180 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bac0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:47,709 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9b0a0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:13:54,997 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9bd00>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:14:01,293 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4b9a980>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:14:08,206 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb27d0>: Failed to establish a new connection: [Errno -2] Name or service not known'))
2024-03-27 13:14:14,501 - ERROR - HTTPConnectionPool(host='10.30.22.11.5340', port=80): Max retries exceeded with url: /vending_status/?ip_address=192.168.18.110 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x79c9a4bb3b80>: Failed to establish a new connection: [Errno -2] Name or service not known'))
